// Item charges fixes

COPY_EXISTING_REGEXP ~^.+\.cre$~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x2d3) BEGIN
    PATCH_FOR_EACH ~item~ IN // Wands
      ~WAND02~   // Wand of Fear
      ~WAND03~   // Wand of Magic Missile
      ~WAND04~   // Wand of Paralyzation
      ~WAND05~   // Wand of Fire
      ~WAND06~   // Wand of Frost
      ~WAND07~   // Wand of Lightning
      ~WAND08~   // Wand of Sleep
      ~WAND09~   // Wand of Polymorphing
      ~WAND10~   // Wand of Monster Summoning
      ~WAND11~   // Wand of the Heavens
      ~WAND12~   // Wand of Magic Missiles (BGEE)
      ~BGWAND12~ // Wand of Magic Missiles (BGT)
      ~WAND12_~  // Wand of Magic Missiles (EET)
      ~WAND13~   // Wand of Cloudkill
      ~WAND18~   // Wand of Spell Striking
      ~WAND19~   // Wand of Cursing
      ~BDWAND01~ // Wand of Water Elemental Summoning (BGSOD)
    BEGIN
      PATCH_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
        GET_OFFSET_ARRAY itm_array CRE_V10_ITEMS
        PHP_EACH ~itm_array~ AS ~int~ => ~itm_offset~ BEGIN
          READ_ASCII (itm_offset + 0x0) resref
          PATCH_IF (~%resref%~ STRING_EQUAL_CASE ~%item%~) BEGIN
            READ_SHORT (itm_offset + 0xa) charges_1
            PATCH_IF (charges_1 > 10) BEGIN
              PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, primary charges: %charges_1% => setting them to 10..."
              WRITE_SHORT (itm_offset + 0xa) 10
            END
          END
        END
      END
    END
    PATCH_FOR_EACH ~item~ IN // 1 charge, 1st header
      ~AMUL20~   // Kaligum's Amulet of Magic Resistance
      ~AMUL25~   // Amulet of Spell Warding
      ~AMUL26~   // Amulet of Cheetah Speed
      ~BELT09~   // Girdle of Trollish Fortitude
      ~BOOT09~   // Boots of the Shifting Sands
      ~BOOT11~   // Boots of Etherealness
      ~BRAC16~   // Bracers of the Blinding Strike
      ~BRAC20~   // Gauntlets of Healing
      ~BRAC23~   // Blessed Bracers
      ~CHAN10~   // Prismatic Chain +4
      ~CLCK04~   // Cloak of the Wolf
      ~CLCK07~   // Cloak of the Nymph
      ~CCLCK08~  // Algernon's Cloak
      ~CLCK27~   // Cloak of the Sewers
      ~HELM16~   // Helm of Brilliance
      ~HELM17~   // Skull of Death
      ~HELM18~   // Pearly White Ioun Stone
      ~HELM30~   // Master Thief's Hood
      ~LEAT18~   // Armor of the Viper +4
      ~MISC2P~   // Greagan's Harp
      ~MISC3A~   // Book of Infinite Spells
      ~MISC3C~   // Efreeti Bottle
      ~MISC3D~   // Golden Lion Figurine
      ~MISC3E~   // Black Spider Figurine
      ~MISC3F~   // Jade Hound Figurine
      ~MISC3I~   // Silver Horn of Valhalla
      ~MISC3J~   // Bronze Horn of Valhalla
      ~MISC3K~   // Iron Horn of Valhalla
      ~MISC73~   // The Horn of Kazgaroth
      ~MISC7T~   // Moon Dog Figurine
      ~MISC7Y~   // Thrall Collar
      ~FIGURE01~ // Shakti Figurine
      ~TOME01~   // Flesh Golem Manual
      ~TOME02~   // Clay Golem Manual
      ~TOME03~   // Stone Golem Manual
      ~TOME04~   // Juggernaut Golem Manual
      ~NPMISC1~  // Jansen Spectroscopes
      ~NPSHLD~   // Delryn Family Shield +2
      ~VICARM~   // Shar's Blessing +5
      ~RING20~   // Ring of Energy
      ~RING26~   // Ring of Djinni Summoning
      ~RING27~   // Ring of Fire Control
      ~RING28~   // Ring of Air Control
      ~RING29~   // Ring of Earth Control
      ~RING30~   // Ring of Human Influence
      ~RING34~   // Ring of Spell Turning
      ~RING42~   // Ring of the Wraith
      ~RODS01~   // Rod of Absorption
      ~RODS03~   // Rod of Resurrection
      ~RODS06~   // Rod of Reversal
      ~WA2HELM~  // Shadow Veil
      ~WAND14~   // Web Sack
      ~WAND15~   // Rod of the Apprenti
    BEGIN
      PATCH_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
        GET_OFFSET_ARRAY itm_array CRE_V10_ITEMS
        PHP_EACH ~itm_array~ AS ~int~ => ~itm_offset~ BEGIN
          READ_ASCII (itm_offset + 0x0) resref
          PATCH_IF (~%resref%~ STRING_EQUAL_CASE ~%item%~) BEGIN
            READ_SHORT (itm_offset + 0xa) charges_1
            PATCH_IF (charges_1 > 1) BEGIN
              PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, primary charges: %charges_1% => setting them to 1..."
              WRITE_SHORT (itm_offset + 0xa) 1
    		END
            PATCH_IF (charges_1 < 1) BEGIN
              PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, primary charges: %charges_1% => setting them to 1..."
              WRITE_SHORT (itm_offset + 0xa) 1
    		END
          END
        END
      END
    END
    PATCH_FOR_EACH ~item~ IN // 1 charge, 2nd header
      ~BLUN27~   // Club of Detonation +5 (2nd)
      ~BOW20~    // Darkfire Bow +4 (2nd)
      ~BOW21~    // Darkfire Bow +5 (2nd)
      ~BRAC23~   // Blessed Bracers (2nd)
      ~CLCK27~   // Cloak of the Sewers (2nd)
      ~HAMM11~   // Runehammer +5 (2nd)
      ~HELM16~   // Helm of Brilliance (2nd)
      ~MISC5T~   // Shaman's Staff (2nd)
      ~RING27~   // Ring of Fire Control (2nd)
      ~RING28~   // Ring of Air Control (2nd)
      ~RING29~   // Ring of Earth Control (2nd)
      ~RING39~   // Ring of Kangaxx (2nd)
      ~STAF09~   // Staff of Command +3 (2nd)
      ~STAF10~   // Staff of Curing +1 (2nd)
      ~STAF12~   // Staff of Power +3 (2nd)
      ~STAF13~   // Staff of Thunder and Lightning +2 (2nd)
      ~STAF14~   // Staff of the Woodlands (2nd)
      ~STAF15~   // Staff of Air +2 (2nd)
      ~STAF16~   // Staff of Earth +2 (2nd)
      ~STAF17~   // Staff of Fire +2 (2nd)
      ~STAF20~   // Staff of Rynn +3 (2nd)
      ~SW1H26~   // Ilbratha +1 (2nd)
      ~SW1H31~   // Daystar +4 (2nd)
      ~SW1H33~   // Ras +2 (2nd)
      ~SW1H64~   // Purifier +5 (2nd)
      ~SW1H68~   // Spectral Brand +4 (2nd)
      ~SW1H69~   // Spectral Brand +5 (2nd)
      ~SW1H70~   // Hindo's Doom +4 (2nd)
      ~SW2H10~   // Carsomyr +4 (2nd)
      ~WAND15~   // Rod of the Apprenti (2nd)
    BEGIN
      PATCH_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
        GET_OFFSET_ARRAY itm_array CRE_V10_ITEMS
        PHP_EACH ~itm_array~ AS ~int~ => ~itm_offset~ BEGIN
          READ_ASCII (itm_offset + 0x0) resref
          PATCH_IF (~%resref%~ STRING_EQUAL_CASE ~%item%~) BEGIN
            READ_SHORT (itm_offset + 0xc) charges_2
            PATCH_IF (charges_2 > 1) BEGIN
              PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, secondary charges: %charges_2% => setting them to 1..."
              WRITE_SHORT (itm_offset + 0xc) 1
    		END
            PATCH_IF (charges_2 < 1) BEGIN
              PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, secondary charges: %charges_2% => setting them to 1..."
              WRITE_SHORT (itm_offset + 0xc) 1
    		END
          END
        END
      END
    END
    PATCH_FOR_EACH ~item~ IN // 1 charge, 3rd header
      ~HAMM11~   // Runehammer +5 (3rd)
      ~HELM16~   // Helm of Brilliance (3rd)
      ~STAF11~   // Staff of the Magi +5 (3rd)
      ~STAF12~   // Staff of Power +3 (3rd)
      ~STAF13~   // Staff of Thunder and Lightning +2 (3rd)
      ~STAF14~   // Staff of the Woodlands (3rd)
      ~SW1H51~   // Celestial Fury (3rd)
      ~SW1H65~   // Purifier +5 (3rd)
      ~SW1H69~   // Spectral Brand +5 (3rd)
      ~SW1H70~   // Hindo's Doom +5 (3rd)
      ~WAND15~   // Rod of the Apprenti (3rd)
    BEGIN
      PATCH_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
        GET_OFFSET_ARRAY itm_array CRE_V10_ITEMS
        PHP_EACH ~itm_array~ AS ~int~ => ~itm_offset~ BEGIN
          READ_ASCII (itm_offset + 0x0) resref
          PATCH_IF (~%resref%~ STRING_EQUAL_CASE ~%item%~) BEGIN
            READ_SHORT (itm_offset + 0xe) charges_3
            PATCH_IF (charges_3 > 1) BEGIN
              PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, tertiary charges: %charges_3% => setting them to 1..."
              WRITE_SHORT (itm_offset + 0xe) 1
    		END
            PATCH_IF (charges_3 < 1) BEGIN
              PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, tertiary charges: %charges_3% => setting them to 1..."
              WRITE_SHORT (itm_offset + 0xe) 1
    		END
          END
        END
      END
    END
    PATCH_FOR_EACH ~item~ IN // 3 charges, 1st header
      ~HELM31~   // Horned Helm of the Rock
      ~MISC3H~   // Horn of Blasting
      ~MISC3L~   // Horn of Silence
      ~MISC3M~   // Harp of Discord
      ~MISC3N~   // Azlaer's Harp
      ~MISC3O~   // Methild's Harp
      ~MISC3P~   // Glasses of Identification
      ~RING05~   // Ring of Invisibility
      ~RING33~   // Ring of the Ram
      ~RING39~   // Ring of Kangaxx
      ~WAND12~   // Rod of Wonder
      ~REGISAMU~ // Ruby Pendant of Beguiling
      ~WA2HARP~  // Harp of Pandemonium
    BEGIN
      PATCH_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
        GET_OFFSET_ARRAY itm_array CRE_V10_ITEMS
        PHP_EACH ~itm_array~ AS ~int~ => ~itm_offset~ BEGIN
          READ_ASCII (itm_offset + 0x0) resref
          PATCH_IF (~%resref%~ STRING_EQUAL_CASE ~%item%~) BEGIN
            READ_SHORT (itm_offset + 0xa) charges_1
            PATCH_IF (charges_1 > 3) BEGIN
              PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, primary charges: %charges_1% => setting them to 3..."
              WRITE_SHORT (itm_offset + 0xa) 3
    		END
            PATCH_IF (charges_1 < 3) BEGIN
              PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, primary charges: %charges_1% => setting them to 3..."
              WRITE_SHORT (itm_offset + 0xa) 3
    		END
          END
        END
      END
    END
    PATCH_FOR_EACH ~item~ IN // 3 charges, 2nd header
      ~STAF11~   // Staff of the Magi +5 (2nd)
      ~SW1H51~   // Celestial Fury (2nd)
    BEGIN
      PATCH_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
        GET_OFFSET_ARRAY itm_array CRE_V10_ITEMS
        PHP_EACH ~itm_array~ AS ~int~ => ~itm_offset~ BEGIN
          READ_ASCII (itm_offset + 0x0) resref
          PATCH_IF (~%resref%~ STRING_EQUAL_CASE ~%item%~) BEGIN
            READ_SHORT (itm_offset + 0xc) charges_2
            PATCH_IF (charges_2 > 3) BEGIN
              PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, primary charges: %charges_2% => setting them to 3..."
              WRITE_SHORT (itm_offset + 0xc) 3
    		END
            PATCH_IF (charges_2 < 3) BEGIN
              PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, primary charges: %charges_2% => setting them to 3..."
              WRITE_SHORT (itm_offset + 0xc) 3
    		END
          END
        END
      END
    END
  END
BUT_ONLY

COPY_EXISTING_REGEXP ~^.+\.sto$~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x9b) BEGIN
    PATCH_FOR_EACH ~item~ IN // Wands
      ~WAND02~   // Wand of Fear
      ~WAND03~   // Wand of Magic Missile
      ~WAND04~   // Wand of Paralyzation
      ~WAND05~   // Wand of Fire
      ~WAND06~   // Wand of Frost
      ~WAND07~   // Wand of Lightning
      ~WAND08~   // Wand of Sleep
      ~WAND09~   // Wand of Polymorphing
      ~WAND10~   // Wand of Monster Summoning
      ~WAND11~   // Wand of the Heavens
      ~WAND12~   // Wand of Magic Missiles (BGEE)
      ~BGWAND12~ // Wand of Magic Missiles (BGT)
      ~WAND12_~  // Wand of Magic Missiles (EET)
      ~WAND13~   // Wand of Cloudkill
      ~WAND18~   // Wand of Spell Striking
      ~WAND19~   // Wand of Cursing
      ~BDWAND01~ // Wand of Water Elemental Summoning (BGSOD)
    BEGIN
      PATCH_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
        GET_OFFSET_ARRAY itm_array STO_V10_ITEMS_SOLD
        PHP_EACH ~itm_array~ AS ~int~ => ~itm_offset~ BEGIN
          READ_ASCII (itm_offset + 0x0) resref
          PATCH_IF (~%resref%~ STRING_EQUAL_CASE ~%item%~) BEGIN
            READ_SHORT (itm_offset + 0xa) charges_1
            PATCH_IF (charges_1 > 10) BEGIN
              PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, primary charges: %charges_1% => setting them to 10..."
              WRITE_SHORT (itm_offset + 0xa) 10
            END
          END
        END
      END
    END
    PATCH_FOR_EACH ~item~ IN // 1 charge, 1st header
      ~AMUL20~   // Kaligum's Amulet of Magic Resistance
      ~AMUL25~   // Amulet of Spell Warding
      ~AMUL26~   // Amulet of Cheetah Speed
      ~BELT09~   // Girdle of Trollish Fortitude
      ~BOOT09~   // Boots of the Shifting Sands
      ~BOOT11~   // Boots of Etherealness
      ~BRAC16~   // Bracers of the Blinding Strike
      ~BRAC20~   // Gauntlets of Healing
      ~BRAC23~   // Blessed Bracers
      ~CHAN10~   // Prismatic Chain +4
      ~CLCK04~   // Cloak of the Wolf
      ~CLCK07~   // Cloak of the Nymph
      ~CCLCK08~  // Algernon's Cloak
      ~CLCK27~   // Cloak of the Sewers
      ~HELM16~   // Helm of Brilliance
      ~HELM17~   // Skull of Death
      ~HELM18~   // Pearly White Ioun Stone
      ~HELM30~   // Master Thief's Hood
      ~LEAT18~   // Armor of the Viper +4
      ~MISC2P~   // Greagan's Harp
      ~MISC3A~   // Book of Infinite Spells
      ~MISC3C~   // Efreeti Bottle
      ~MISC3D~   // Golden Lion Figurine
      ~MISC3E~   // Black Spider Figurine
      ~MISC3F~   // Jade Hound Figurine
      ~MISC3I~   // Silver Horn of Valhalla
      ~MISC3J~   // Bronze Horn of Valhalla
      ~MISC3K~   // Iron Horn of Valhalla
      ~MISC73~   // The Horn of Kazgaroth
      ~MISC7T~   // Moon Dog Figurine
      ~MISC7Y~   // Thrall Collar
      ~FIGURE01~ // Shakti Figurine
      ~TOME01~   // Flesh Golem Manual
      ~TOME02~   // Clay Golem Manual
      ~TOME03~   // Stone Golem Manual
      ~TOME04~   // Juggernaut Golem Manual
      ~NPMISC1~  // Jansen Spectroscopes
      ~NPSHLD~   // Delryn Family Shield +2
      ~VICARM~   // Shar's Blessing +5
      ~RING20~   // Ring of Energy
      ~RING26~   // Ring of Djinni Summoning
      ~RING27~   // Ring of Fire Control
      ~RING28~   // Ring of Air Control
      ~RING29~   // Ring of Earth Control
      ~RING30~   // Ring of Human Influence
      ~RING34~   // Ring of Spell Turning
      ~RING42~   // Ring of the Wraith
      ~RODS01~   // Rod of Absorption
      ~RODS03~   // Rod of Resurrection
      ~RODS06~   // Rod of Reversal
      ~WA2HELM~  // Shadow Veil
      ~WAND14~   // Web Sack
      ~WAND15~   // Rod of the Apprenti
    BEGIN
      PATCH_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
        GET_OFFSET_ARRAY itm_array STO_V10_ITEMS_SOLD
        PHP_EACH ~itm_array~ AS ~int~ => ~itm_offset~ BEGIN
          READ_ASCII (itm_offset + 0x0) resref
          PATCH_IF (~%resref%~ STRING_EQUAL_CASE ~%item%~) BEGIN
            READ_SHORT (itm_offset + 0xa) charges_1
            PATCH_IF (charges_1 > 1) BEGIN
              PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, primary charges: %charges_1% => setting them to 1..."
              WRITE_SHORT (itm_offset + 0xa) 1
    		END
            PATCH_IF (charges_1 < 1) BEGIN
              PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, primary charges: %charges_1% => setting them to 1..."
              WRITE_SHORT (itm_offset + 0xa) 1
    		END
          END
        END
      END
    END
    PATCH_FOR_EACH ~item~ IN // 1 charge, 2nd header
      ~BLUN27~   // Club of Detonation +5 (2nd)
      ~BOW20~    // Darkfire Bow +4 (2nd)
      ~BOW21~    // Darkfire Bow +5 (2nd)
      ~BRAC23~   // Blessed Bracers (2nd)
      ~CLCK27~   // Cloak of the Sewers (2nd)
      ~HAMM11~   // Runehammer +5 (2nd)
      ~HELM16~   // Helm of Brilliance (2nd)
      ~MISC5T~   // Shaman's Staff (2nd)
      ~RING27~   // Ring of Fire Control (2nd)
      ~RING28~   // Ring of Air Control (2nd)
      ~RING29~   // Ring of Earth Control (2nd)
      ~RING39~   // Ring of Kangaxx (2nd)
      ~STAF09~   // Staff of Command +3 (2nd)
      ~STAF10~   // Staff of Curing +1 (2nd)
      ~STAF12~   // Staff of Power +3 (2nd)
      ~STAF13~   // Staff of Thunder and Lightning +2 (2nd)
      ~STAF14~   // Staff of the Woodlands (2nd)
      ~STAF15~   // Staff of Air +2 (2nd)
      ~STAF16~   // Staff of Earth +2 (2nd)
      ~STAF17~   // Staff of Fire +2 (2nd)
      ~STAF20~   // Staff of Rynn +3 (2nd)
      ~SW1H26~   // Ilbratha +1 (2nd)
      ~SW1H31~   // Daystar +4 (2nd)
      ~SW1H33~   // Ras +2 (2nd)
      ~SW1H64~   // Purifier +5 (2nd)
      ~SW1H68~   // Spectral Brand +4 (2nd)
      ~SW1H69~   // Spectral Brand +5 (2nd)
      ~SW1H70~   // Hindo's Doom +4 (2nd)
      ~SW2H10~   // Carsomyr +4 (2nd)
      ~WAND15~   // Rod of the Apprenti (2nd)
    BEGIN
      PATCH_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
        GET_OFFSET_ARRAY itm_array STO_V10_ITEMS_SOLD
        PHP_EACH ~itm_array~ AS ~int~ => ~itm_offset~ BEGIN
          READ_ASCII (itm_offset + 0x0) resref
          PATCH_IF (~%resref%~ STRING_EQUAL_CASE ~%item%~) BEGIN
            READ_SHORT (itm_offset + 0xc) charges_2
            PATCH_IF (charges_2 > 1) BEGIN
              PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, secondary charges: %charges_2% => setting them to 1..."
              WRITE_SHORT (itm_offset + 0xc) 1
    		END
            PATCH_IF (charges_2 < 1) BEGIN
              PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, secondary charges: %charges_2% => setting them to 1..."
              WRITE_SHORT (itm_offset + 0xc) 1
    		END
          END
        END
      END
    END
    PATCH_FOR_EACH ~item~ IN // 1 charge, 3rd header
      ~HAMM11~   // Runehammer +5 (3rd)
      ~HELM16~   // Helm of Brilliance (3rd)
      ~STAF11~   // Staff of the Magi +5 (3rd)
      ~STAF12~   // Staff of Power +3 (3rd)
      ~STAF13~   // Staff of Thunder and Lightning +2 (3rd)
      ~STAF14~   // Staff of the Woodlands (3rd)
      ~SW1H51~   // Celestial Fury (3rd)
      ~SW1H65~   // Purifier +5 (3rd)
      ~SW1H69~   // Spectral Brand +5 (3rd)
      ~SW1H70~   // Hindo's Doom +5 (3rd)
      ~WAND15~   // Rod of the Apprenti (3rd)
    BEGIN
      PATCH_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
        GET_OFFSET_ARRAY itm_array STO_V10_ITEMS_SOLD
        PHP_EACH ~itm_array~ AS ~int~ => ~itm_offset~ BEGIN
          READ_ASCII (itm_offset + 0x0) resref
          PATCH_IF (~%resref%~ STRING_EQUAL_CASE ~%item%~) BEGIN
            READ_SHORT (itm_offset + 0xe) charges_3
            PATCH_IF (charges_3 > 1) BEGIN
              PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, tertiary charges: %charges_3% => setting them to 1..."
              WRITE_SHORT (itm_offset + 0xe) 1
    		END
            PATCH_IF (charges_3 < 1) BEGIN
              PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, tertiary charges: %charges_3% => setting them to 1..."
              WRITE_SHORT (itm_offset + 0xe) 1
    		END
          END
        END
      END
    END
    PATCH_FOR_EACH ~item~ IN // 3 charges, 1st header
      ~HELM31~   // Horned Helm of the Rock
      ~MISC3H~   // Horn of Blasting
      ~MISC3L~   // Horn of Silence
      ~MISC3M~   // Harp of Discord
      ~MISC3N~   // Azlaer's Harp
      ~MISC3O~   // Methild's Harp
      ~MISC3P~   // Glasses of Identification
      ~RING05~   // Ring of Invisibility
      ~RING33~   // Ring of the Ram
      ~RING39~   // Ring of Kangaxx
      ~WAND12~   // Rod of Wonder
      ~REGISAMU~ // Ruby Pendant of Beguiling
      ~WA2HARP~  // Harp of Pandemonium
    BEGIN
      PATCH_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
        GET_OFFSET_ARRAY itm_array STO_V10_ITEMS_SOLD
        PHP_EACH ~itm_array~ AS ~int~ => ~itm_offset~ BEGIN
          READ_ASCII (itm_offset + 0x0) resref
          PATCH_IF (~%resref%~ STRING_EQUAL_CASE ~%item%~) BEGIN
            READ_SHORT (itm_offset + 0xa) charges_1
            PATCH_IF (charges_1 > 3) BEGIN
              PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, primary charges: %charges_1% => setting them to 3..."
              WRITE_SHORT (itm_offset + 0xa) 3
    		END
            PATCH_IF (charges_1 < 3) BEGIN
              PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, primary charges: %charges_1% => setting them to 3..."
              WRITE_SHORT (itm_offset + 0xa) 3
    		END
          END
        END
      END
    END
    PATCH_FOR_EACH ~item~ IN // 3 charges, 2nd header
      ~STAF11~   // Staff of the Magi +5 (2nd)
      ~SW1H51~   // Celestial Fury (2nd)
    BEGIN
      PATCH_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
        GET_OFFSET_ARRAY itm_array STO_V10_ITEMS_SOLD
        PHP_EACH ~itm_array~ AS ~int~ => ~itm_offset~ BEGIN
          READ_ASCII (itm_offset + 0x0) resref
          PATCH_IF (~%resref%~ STRING_EQUAL_CASE ~%item%~) BEGIN
            READ_SHORT (itm_offset + 0xc) charges_2
            PATCH_IF (charges_2 > 3) BEGIN
              PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, primary charges: %charges_2% => setting them to 3..."
              WRITE_SHORT (itm_offset + 0xc) 3
    		END
            PATCH_IF (charges_2 < 3) BEGIN
              PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, primary charges: %charges_2% => setting them to 3..."
              WRITE_SHORT (itm_offset + 0xc) 3
    		END
          END
        END
      END
    END
  END
BUT_ONLY

COPY_EXISTING_REGEXP ~^.+\.are$~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x11b) BEGIN
    PATCH_FOR_EACH ~item~ IN // Wands
      ~WAND02~   // Wand of Fear
      ~WAND03~   // Wand of Magic Missile
      ~WAND04~   // Wand of Paralyzation
      ~WAND05~   // Wand of Fire
      ~WAND06~   // Wand of Frost
      ~WAND07~   // Wand of Lightning
      ~WAND08~   // Wand of Sleep
      ~WAND09~   // Wand of Polymorphing
      ~WAND10~   // Wand of Monster Summoning
      ~WAND11~   // Wand of the Heavens
      ~WAND12~   // Wand of Magic Missiles (BGEE)
      ~BGWAND12~ // Wand of Magic Missiles (BGT)
      ~WAND12_~  // Wand of Magic Missiles (EET)
      ~WAND13~   // Wand of Cloudkill
      ~WAND18~   // Wand of Spell Striking
      ~WAND19~   // Wand of Cursing
      ~BDWAND01~ // Wand of Water Elemental Summoning (BGSOD)
    BEGIN
      PATCH_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
        GET_OFFSET_ARRAY container_array ARE_V10_CONTAINERS
        PHP_EACH ~container_array~ AS ~int~ => ~container_offset~ BEGIN
          GET_OFFSET_ARRAY2 itm_array container_offset ARE_V10_ITEMS
          PHP_EACH ~itm_array~ AS ~int~ => ~itm_offset~ BEGIN
            READ_ASCII (itm_offset + 0x0) resref
            PATCH_IF (~%resref%~ STRING_EQUAL_CASE ~%item%~) BEGIN
              READ_ASCII (container_offset + 0x0) container_name (32) NULL
              READ_SHORT (itm_offset + 0xa) charges_1
              PATCH_IF (charges_1 > 10) BEGIN
                PATCH_PRINT "~%SOURCE_FILE%~: ~%container_name%~, ~%item%.itm~, primary charges: %charges_1% => setting them to 10..."
                WRITE_SHORT (itm_offset + 0xa) 10
              END
            END
          END
        END
      END
    END
    PATCH_FOR_EACH ~item~ IN // 1 charge, 1st header
      ~AMUL20~   // Kaligum's Amulet of Magic Resistance
      ~AMUL25~   // Amulet of Spell Warding
      ~AMUL26~   // Amulet of Cheetah Speed
      ~BELT09~   // Girdle of Trollish Fortitude
      ~BOOT09~   // Boots of the Shifting Sands
      ~BOOT11~   // Boots of Etherealness
      ~BRAC16~   // Bracers of the Blinding Strike
      ~BRAC20~   // Gauntlets of Healing
      ~BRAC23~   // Blessed Bracers
      ~CHAN10~   // Prismatic Chain +4
      ~CLCK04~   // Cloak of the Wolf
      ~CLCK07~   // Cloak of the Nymph
      ~CCLCK08~  // Algernon's Cloak
      ~CLCK27~   // Cloak of the Sewers
      ~HELM16~   // Helm of Brilliance
      ~HELM17~   // Skull of Death
      ~HELM18~   // Pearly White Ioun Stone
      ~HELM30~   // Master Thief's Hood
      ~LEAT18~   // Armor of the Viper +4
      ~MISC2P~   // Greagan's Harp
      ~MISC3A~   // Book of Infinite Spells
      ~MISC3C~   // Efreeti Bottle
      ~MISC3D~   // Golden Lion Figurine
      ~MISC3E~   // Black Spider Figurine
      ~MISC3F~   // Jade Hound Figurine
      ~MISC3I~   // Silver Horn of Valhalla
      ~MISC3J~   // Bronze Horn of Valhalla
      ~MISC3K~   // Iron Horn of Valhalla
      ~MISC73~   // The Horn of Kazgaroth
      ~MISC7T~   // Moon Dog Figurine
      ~MISC7Y~   // Thrall Collar
      ~FIGURE01~ // Shakti Figurine
      ~TOME01~   // Flesh Golem Manual
      ~TOME02~   // Clay Golem Manual
      ~TOME03~   // Stone Golem Manual
      ~TOME04~   // Juggernaut Golem Manual
      ~NPMISC1~  // Jansen Spectroscopes
      ~NPSHLD~   // Delryn Family Shield +2
      ~VICARM~   // Shar's Blessing +5
      ~RING20~   // Ring of Energy
      ~RING26~   // Ring of Djinni Summoning
      ~RING27~   // Ring of Fire Control
      ~RING28~   // Ring of Air Control
      ~RING29~   // Ring of Earth Control
      ~RING30~   // Ring of Human Influence
      ~RING34~   // Ring of Spell Turning
      ~RING42~   // Ring of the Wraith
      ~RODS01~   // Rod of Absorption
      ~RODS03~   // Rod of Resurrection
      ~RODS06~   // Rod of Reversal
      ~WA2HELM~  // Shadow Veil
      ~WAND14~   // Web Sack
      ~WAND15~   // Rod of the Apprenti
    BEGIN
      PATCH_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
        GET_OFFSET_ARRAY container_array ARE_V10_CONTAINERS
        PHP_EACH ~container_array~ AS ~int~ => ~container_offset~ BEGIN
          GET_OFFSET_ARRAY2 itm_array container_offset ARE_V10_ITEMS
          PHP_EACH ~itm_array~ AS ~int~ => ~itm_offset~ BEGIN
            READ_ASCII (itm_offset + 0x0) resref
            PATCH_IF (~%resref%~ STRING_EQUAL_CASE ~%item%~) BEGIN
              READ_ASCII (container_offset + 0x0) container_name (32) NULL
              READ_SHORT (itm_offset + 0xa) charges_1
              PATCH_IF (charges_1 > 1) BEGIN
                PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, primary charges: %charges_1% => setting them to 1..."
                WRITE_SHORT (itm_offset + 0xa) 1
    		  END
              PATCH_IF (charges_1 < 1) BEGIN
                PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, primary charges: %charges_1% => setting them to 1..."
                WRITE_SHORT (itm_offset + 0xa) 1
    		  END
            END
          END
        END
      END
    END
    PATCH_FOR_EACH ~item~ IN // 1 charge, 2nd header
      ~BLUN27~   // Club of Detonation +5 (2nd)
      ~BOW20~    // Darkfire Bow +4 (2nd)
      ~BOW21~    // Darkfire Bow +5 (2nd)
      ~BRAC23~   // Blessed Bracers (2nd)
      ~CLCK27~   // Cloak of the Sewers (2nd)
      ~HAMM11~   // Runehammer +5 (2nd)
      ~HELM16~   // Helm of Brilliance (2nd)
      ~MISC5T~   // Shaman's Staff (2nd)
      ~RING27~   // Ring of Fire Control (2nd)
      ~RING28~   // Ring of Air Control (2nd)
      ~RING29~   // Ring of Earth Control (2nd)
      ~RING39~   // Ring of Kangaxx (2nd)
      ~STAF09~   // Staff of Command +3 (2nd)
      ~STAF10~   // Staff of Curing +1 (2nd)
      ~STAF12~   // Staff of Power +3 (2nd)
      ~STAF13~   // Staff of Thunder and Lightning +2 (2nd)
      ~STAF14~   // Staff of the Woodlands (2nd)
      ~STAF15~   // Staff of Air +2 (2nd)
      ~STAF16~   // Staff of Earth +2 (2nd)
      ~STAF17~   // Staff of Fire +2 (2nd)
      ~STAF20~   // Staff of Rynn +3 (2nd)
      ~SW1H26~   // Ilbratha +1 (2nd)
      ~SW1H31~   // Daystar +4 (2nd)
      ~SW1H33~   // Ras +2 (2nd)
      ~SW1H64~   // Purifier +5 (2nd)
      ~SW1H68~   // Spectral Brand +4 (2nd)
      ~SW1H69~   // Spectral Brand +5 (2nd)
      ~SW1H70~   // Hindo's Doom +4 (2nd)
      ~SW2H10~   // Carsomyr +4 (2nd)
      ~WAND15~   // Rod of the Apprenti (2nd)
    BEGIN
      PATCH_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
        GET_OFFSET_ARRAY container_array ARE_V10_CONTAINERS
        PHP_EACH ~container_array~ AS ~int~ => ~container_offset~ BEGIN
          GET_OFFSET_ARRAY2 itm_array container_offset ARE_V10_ITEMS
          PHP_EACH ~itm_array~ AS ~int~ => ~itm_offset~ BEGIN
            READ_ASCII (itm_offset + 0x0) resref
            PATCH_IF (~%resref%~ STRING_EQUAL_CASE ~%item%~) BEGIN
              READ_ASCII (container_offset + 0x0) container_name (32) NULL
              READ_SHORT (itm_offset + 0xc) charges_2
              PATCH_IF (charges_2 > 1) BEGIN
                PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, secondary charges: %charges_2% => setting them to 1..."
                WRITE_SHORT (itm_offset + 0xc) 1
    		  END
              PATCH_IF (charges_2 < 1) BEGIN
                PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, secondary charges: %charges_2% => setting them to 1..."
                WRITE_SHORT (itm_offset + 0xc) 1
    		  END
            END
          END
        END
      END
    END
    PATCH_FOR_EACH ~item~ IN // 1 charge, 3rd header
      ~HAMM11~   // Runehammer +5 (3rd)
      ~HELM16~   // Helm of Brilliance (3rd)
      ~STAF11~   // Staff of the Magi +5 (3rd)
      ~STAF12~   // Staff of Power +3 (3rd)
      ~STAF13~   // Staff of Thunder and Lightning +2 (3rd)
      ~STAF14~   // Staff of the Woodlands (3rd)
      ~SW1H51~   // Celestial Fury (3rd)
      ~SW1H65~   // Purifier +5 (3rd)
      ~SW1H69~   // Spectral Brand +5 (3rd)
      ~SW1H70~   // Hindo's Doom +5 (3rd)
      ~WAND15~   // Rod of the Apprenti (3rd)
    BEGIN
      PATCH_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
        GET_OFFSET_ARRAY container_array ARE_V10_CONTAINERS
        PHP_EACH ~container_array~ AS ~int~ => ~container_offset~ BEGIN
          GET_OFFSET_ARRAY2 itm_array container_offset ARE_V10_ITEMS
          PHP_EACH ~itm_array~ AS ~int~ => ~itm_offset~ BEGIN
            READ_ASCII (itm_offset + 0x0) resref
            PATCH_IF (~%resref%~ STRING_EQUAL_CASE ~%item%~) BEGIN
              READ_ASCII (container_offset + 0x0) container_name (32) NULL
              READ_SHORT (itm_offset + 0xe) charges_3
              PATCH_IF (charges_3 > 1) BEGIN
                PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, tertiary charges: %charges_3% => setting them to 1..."
                WRITE_SHORT (itm_offset + 0xe) 1
    		  END
              PATCH_IF (charges_3 < 1) BEGIN
                PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, tertiary charges: %charges_3% => setting them to 1..."
                WRITE_SHORT (itm_offset + 0xe) 1
    		  END
            END
          END
        END
      END
    END
    PATCH_FOR_EACH ~item~ IN // 3 charges, 1st header
      ~HELM31~   // Horned Helm of the Rock
      ~MISC3H~   // Horn of Blasting
      ~MISC3L~   // Horn of Silence
      ~MISC3M~   // Harp of Discord
      ~MISC3N~   // Azlaer's Harp
      ~MISC3O~   // Methild's Harp
      ~MISC3P~   // Glasses of Identification
      ~RING05~   // Ring of Invisibility
      ~RING33~   // Ring of the Ram
      ~RING39~   // Ring of Kangaxx
      ~WAND12~   // Rod of Wonder
      ~REGISAMU~ // Ruby Pendant of Beguiling
      ~WA2HARP~  // Harp of Pandemonium
    BEGIN
      PATCH_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
        GET_OFFSET_ARRAY container_array ARE_V10_CONTAINERS
        PHP_EACH ~container_array~ AS ~int~ => ~container_offset~ BEGIN
          GET_OFFSET_ARRAY2 itm_array container_offset ARE_V10_ITEMS
          PHP_EACH ~itm_array~ AS ~int~ => ~itm_offset~ BEGIN
            READ_ASCII (itm_offset + 0x0) resref
            PATCH_IF (~%resref%~ STRING_EQUAL_CASE ~%item%~) BEGIN
              READ_ASCII (container_offset + 0x0) container_name (32) NULL
              READ_SHORT (itm_offset + 0xa) charges_1
              PATCH_IF (charges_1 > 3) BEGIN
                PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, primary charges: %charges_1% => setting them to 3..."
                WRITE_SHORT (itm_offset + 0xa) 3
    		  END
              PATCH_IF (charges_1 < 3) BEGIN
                PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, primary charges: %charges_1% => setting them to 3..."
                WRITE_SHORT (itm_offset + 0xa) 3
    		  END
            END
          END
        END
      END
    END
    PATCH_FOR_EACH ~item~ IN // 3 charges, 2nd header
      ~STAF11~   // Staff of the Magi +5 (2nd)
      ~SW1H51~   // Celestial Fury (2nd)
    BEGIN
      PATCH_IF (FILE_EXISTS_IN_GAME ~%item%.itm~) BEGIN
        GET_OFFSET_ARRAY container_array ARE_V10_CONTAINERS
        PHP_EACH ~container_array~ AS ~int~ => ~container_offset~ BEGIN
          GET_OFFSET_ARRAY2 itm_array container_offset ARE_V10_ITEMS
          PHP_EACH ~itm_array~ AS ~int~ => ~itm_offset~ BEGIN
            READ_ASCII (itm_offset + 0x0) resref
            PATCH_IF (~%resref%~ STRING_EQUAL_CASE ~%item%~) BEGIN
              READ_ASCII (container_offset + 0x0) container_name (32) NULL
              READ_SHORT (itm_offset + 0xc) charges_2
              PATCH_IF (charges_2 > 3) BEGIN
                PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, primary charges: %charges_2% => setting them to 3..."
                WRITE_SHORT (itm_offset + 0xc) 3
    		  END
              PATCH_IF (charges_2 < 3) BEGIN
                PATCH_PRINT "~%SOURCE_FILE%~: ~%item%.itm~, primary charges: %charges_2% => setting them to 3..."
                WRITE_SHORT (itm_offset + 0xc) 3
    		  END
            END
          END
        END
      END
    END
  END
BUT_ONLY